version: '3'

services:
  zakzk:
    container_name: zakzk
    build:
      context: ./
      dockerfile: Dockerfile
    image: zakzk:alpha
    restart: unless-stopped
    volumes:
      - '.:/usr/src/app'
    network_mode: host
    expose:
      - 3001:3001
