version: '3'

services:
  zakzk:
    container_name: zakzk
    build:
      dockerfile: Dockerfile
    image: zakzk:alpha
    restart: unless-stopped
    volumes:
      - '.:/usr/src/app'
    ports:
      - 3001:3001
